name: flutter_symbols
description: "Apple SF Symbols 6 as Flutter IconData. 8000+ icons for Apple platforms."
version: 1.0.0
homepage: https://github.com/fitpage-tech/flutter_symbols

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - icons
  - sf-symbols
  - apple
  - ui
  - fonts

flutter:
  fonts:
    - family: SFSymbols
      fonts:
        - asset: lib/fonts/SFSymbols.ttf
